# House Price Prediction

Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Load Dataset

In [2]:
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\house price prediction.csv")
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [4]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [5]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [6]:
df.isna().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

Data Preprocessing

In [9]:
X=df[["bedrooms","bathrooms","sqft_living","floors","condition","yr_built"]]
y=df["price"]
print("Feature Variables:",X.shape)
print("Target Feature",y.shape)

Feature Variables: (4600, 6)
Target Feature (4600,)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit_transform(X)

array([[-0.44112227, -0.84320364, -0.82997105, -0.02241648, -0.6671122 ,
        -0.53101376],
       [ 1.75970468,  0.43280154,  1.56852826,  0.90655464,  2.28641631,
        -1.67469295],
       [-0.44112227, -0.20520105, -0.21736733, -0.9513876 ,  0.80965205,
        -0.1609999 ],
       ...,
       [-0.44112227,  0.43280154,  0.90400897,  0.90655464, -0.6671122 ,
         1.2854179 ],
       [ 0.6592912 , -0.20520105, -0.05123751, -0.9513876 , -0.6671122 ,
         0.10810108],
       [-0.44112227,  0.43280154, -0.67422434,  0.90655464,  0.80965205,
         0.64630305]])

Feature Engineering

In [16]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print("Training Date:")
print(x_train,y_train)

Training Date:
      bedrooms  bathrooms  sqft_living  floors  condition  yr_built
1898       4.0       2.50         2770     2.0          4      1989
1370       4.0       3.00         3720     2.0          3      1991
3038       4.0       2.50         2810     2.0          3      1982
2361       4.0       3.75         4030     2.0          3      2006
156        3.0       2.00         2000     2.0          3      1916
...        ...        ...          ...     ...        ...       ...
4426       3.0       1.00         1180     1.5          3      1946
466        4.0       2.00         2520     1.0          3      1921
3092       3.0       1.00         1150     1.0          4      1932
3772       2.0       1.00          910     1.5          3      1900
860        2.0       1.00         1490     1.0          3      1929

[3680 rows x 6 columns] 1898    6.850000e+05
1370    8.570000e+05
3038    6.750000e+05
2361    1.485000e+06
156     5.610000e+05
            ...
4426    2.825089e+05
466     8.750000e+05
3092    2.900000e+05
3772    6.000000e+05
860     4.750000e+05
Name: price, Length: 3680, dtype: float64

In [17]:
print("Testing data:")
print(x_test,y_test)

Testing data:
      bedrooms  bathrooms  sqft_living  floors  condition  yr_built
3683       3.0       2.50         1460     2.0          3      2007
4411       5.0       2.25         2000     1.0          4      1986
2584       3.0       3.25         2940     3.0          4      1978
69         3.0       2.50         2200     1.0          5      1988
1844       3.0       2.50         1720     1.0          3      1983
...        ...        ...          ...     ...        ...       ...
1612       3.0       1.75         1700     1.0          3      1947
1068       5.0       2.00         1930     1.5          3      1941
4350       3.0       2.00         1180     1.0          4      1992
3027       4.0       2.50         2370     2.0          5      1966
3455       4.0       2.25         2260     2.0          4      1984

[920 rows x 6 columns] 3683      544000.0
4411           0.0
2584     1712500.0
69        365000.0
1844      275000.0
           ...
1612      750000.0
1068      230000.0
4350    26590000.0
3027      687000.0
3455      289659.0
Name: price, Length: 920, dtype: float64

Model Selection and Training

In [20]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(x_train,y_train)
y_test_pred=model.predict(x_test)
y_pred_all=model.predict(X)